fix POST on eventadmincontroller
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #127
Opened 2020-12-22 15:23 UTC by calouvts

2020-12-22 15:26 UTC, MaevaPllt approved these changes

2020-12-23 12:21 UTC, sblondeau requested changes

2020-12-23 12:21 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +     * @Route("/edit/{id}", name="edit", methods={"POST"})
non l'edit n'est pas que en POST, quand tu accèdes à la page d'edition, tu es en GET et quand tu y réaccède après avoir soumis le form là tu es en POST. Ne mets pas le methods dans la route.

2020-12-23 12:21 UTC, sblondeau commented on src/Controller/AdminEventController.php
>       * @ParamConverter("event", class="App\Entity\Event", options={"mapping": {"id": "id"}})
le @paramConverter est aussi à retirer, là tu as typer dans ta méthode en Event $event donc il n'y a pas besoin de spécifier la classe App\Entity\Event

2020-12-23 14:14 UTC, closed without merging