S03US20_sophrology_presentation
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #129
Opened 2020-12-25 22:45 UTC by MaevaPllt

2020-12-26 13:38 UTC, calouvts submitted a review, later dismissed

2020-12-28 19:26 UTC, sblondeau requested changes

2020-12-28 19:26 UTC, sblondeau commented on templates/sophrology/index.html.twig
> +                <span class="strongWord">détente musculaire</span> et de <span class="strongWord">visualisationmentale positive</span>. Elle s’appuie sur des techniques occidentales (hypnose, autosug
pourquoi ne pas mettre direct une balise `<strong>` ?

2020-12-28 19:26 UTC, sblondeau commented on assets/styles/sophrology.scss
> +.strongWord {
à enlever (voir comment plus bas)

2020-12-28 19:35 UTC, sblondeau approved these changes

2020-12-28 19:35 UTC, merged