S03us55 login page
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #131
Opened 2020-12-29 14:22 UTC by KevinVanphavong

2020-12-31 13:02 UTC, calouvts submitted a review, later dismissed

2021-01-02 12:20 UTC, sblondeau requested changes

2021-01-02 12:20 UTC, sblondeau commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=180, unique=true)
ajoute les @Assert qui vont bien sur chacune de ces propriétés

2021-01-02 12:20 UTC, sblondeau requested changes

2021-01-02 12:20 UTC, sblondeau commented on templates/security/login.html.twig
> +                Sign in
traduction bouton

2021-01-02 14:56 UTC, MaevaPllt submitted a review, later dismissed

2021-01-04 07:54 UTC, sblondeau requested changes

2021-01-04 07:54 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Regex(
non tu as un @Assert\Email qui existe dejà ! 
et pas la peine de traduire les messages d'erreur, suffit de passer Sf en fr (comme indiqué dans quete/LC)

2021-01-04 13:17 UTC, MaevaPllt approved these changes

2021-01-04 14:58 UTC, sblondeau requested changes

2021-01-04 14:58 UTC, sblondeau commented on src/Entity/User.php
> +     *     maxMessage=" Le champ du mail ne peut dépasser {{ limit }} caractères ")
donc c'est ce que je te disais, tous les maxMessage, et message de tes Assert sont à enlever car y a déjà un message par défaut

2021-01-04 16:22 UTC, calouvts approved these changes

2021-01-05 08:41 UTC, sblondeau approved these changes

2021-01-05 08:41 UTC, merged