S03US19_add_section_sophrology_help
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #132
Opened 2020-12-29 22:21 UTC by MaevaPllt

2020-12-30 08:37 UTC, calouvts approved these changes

2020-12-30 13:57 UTC, sblondeau requested changes

2020-12-30 13:57 UTC, sblondeau commented on templates/sophrology/index.html.twig
> +        {% set themes = {
je suis partagé par ton approche via un tableau. Ok c'est bien de ne pas se réptéter, mais là ça ne t'apporte pas grand chose.
déjà es tu sûre que cette page est statique ? (sinon il me faut un table en bdd :p )
si c'est ok, là dans ton tableau themes, déjà tes clés numériques ne servent à rien. Ensuite, c'est pas comme si tu avait beaucoup d'infos différentes à mettre en page, tu n'as qu'un titre et un article... je ne suis pas sûr que ça apporte grand chose; ça rend ton code plus compliqué à lire...

2020-12-30 13:57 UTC, sblondeau commented on templates/sophrology/index.html.twig
> +                <ul class="col-lg-2 col-sm-12 col-11 list-group list-group-flush m-3">
pas logique
là tu gère un col de 11 pour les tailles xs et un col de 12 pour sm (ou plus grand). Pourquoi ne pas mettre en 12 pour les téléphone?

2021-01-01 13:30 UTC, MaevaPllt commented on templates/sophrology/index.html.twig
> +        {% set themes = {
Cette page n'a pas vocation a être administrable, du coup je vais faire 5 cards, ça me permettra de les styliser individuellement, et ça rendra sûrement plus clair :)

2021-01-01 16:39 UTC, calouvts approved these changes

2021-01-04 08:07 UTC, sblondeau approved these changes

2021-01-04 08:08 UTC, merged