S03 us25 detailsseanceindividuel
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #133
Opened 2021-01-01 21:35 UTC by bloic

2021-01-02 08:12 UTC, calouvts submitted a review, later dismissed

2021-01-02 12:25 UTC, sblondeau requested changes
il faut retirer tous ces SVG et travailler avec du texte sur lequel tu fais du CSS ! ça sera beaucoup plus propre

2021-01-02 12:25 UTC, sblondeau commented on assets/images/etape1.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
non ce n'est pas la bonne solution
tu dois faire un bloc de texte simple, puis tu stylise une "flèche" via CSS, mais le texte ne dois pas etre directement inclus dans le svg
par ex clip-path en CSS te permettrait d'avoir cette forme facilement, un ex ic https://bennettfeely.com/clippy/

2021-01-05 20:36 UTC, MaevaPllt submitted a review, later dismissed

2021-01-06 08:28 UTC, sblondeau approved these changes

2021-01-06 10:49 UTC, MaevaPllt approved these changes

2021-01-06 14:52 UTC, merged