S03 us53 event filter client
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #134
Opened 2021-01-02 20:29 UTC by calouvts

2021-01-02 21:14 UTC, MaevaPllt approved these changes

2021-01-04 08:21 UTC, sblondeau requested changes

2021-01-04 08:21 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +    public function archive(Request $request, Event $event): Response
c'est bien d'etre passé par POST c'est bien comme ça qu'il faut faire !
après pour optimiser, plutot que de gérer 2 methodes quasiment identiques, tu peux en avoir qu'une seule que tu appellerais toggleArchive()
et dedans tu modifie simplement la ligne `$event->setArchive(!$event->getArchive())`
avec ça récupère le statut actuel avec le getArchive() (donc true ou false) et avec le "!" ça l'inverse. Donc si le status etait à true, ça met false et vice versa. Donc plus besoin de 2 methodes

2021-01-04 08:21 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +     * @ParamConverter("event", class="App\Entity\Event", options={"mapping": {"id": "id"}})
pas besoin de la ligne @ParamConverter
dans ta route tu n'as qu'un seul {id} et dans ta methode tu type en Event, donc il arrive à faire le lien tout seul.

2021-01-04 15:49 UTC, sblondeau approved these changes

2021-01-04 17:03 UTC, MaevaPllt approved these changes

2021-01-05 08:42 UTC, merged