fix_css_client_color
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #135
Opened 2021-01-04 11:30 UTC by MaevaPllt

2021-01-04 14:11 UTC, calouvts approved these changes

2021-01-04 15:55 UTC, sblondeau requested changes
image accueil.jpeg >1Mo, à reduire grandement

2021-01-04 15:55 UTC, sblondeau commented on assets/styles/app.scss
> +    color: #006D77;
variable pour les couleurs

2021-01-04 16:23 UTC, calouvts approved these changes

2021-01-05 08:42 UTC, sblondeau approved these changes

2021-01-05 08:42 UTC, merged