change_color_contact_page_and_add_jumbotron_style
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #143
Opened 2021-01-05 21:44 UTC by MaevaPllt

2021-01-05 21:57 UTC, bloic approved these changes

2021-01-06 08:30 UTC, sblondeau requested changes
image compass trop  grosse...

2021-01-06 12:15 UTC, bloic approved these changes

2021-01-06 14:53 UTC, sblondeau approved these changes

2021-01-06 15:17 UTC, bloic approved these changes

2021-01-06 19:36 UTC, sblondeau requested changes

2021-01-06 19:36 UTC, sblondeau commented on migrations/Version20210106082902.php
> +declare(strict_types=1);
pourquoi un fichier de migration alors que ta PR ne modifie pas la BDD ? à enlever je pense

2021-01-06 19:37 UTC, merged