crud Add S04_US29
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #163
Opened 2021-01-09 15:54 UTC by bloic

2021-01-09 16:32 UTC, calouvts approved these changes

2021-01-11 08:37 UTC, sblondeau requested changes

2021-01-11 08:37 UTC, sblondeau commented on src/Controller/AdminPricesController.php
> +class AdminPricesController extends AbstractController
nom d'entité tjs au SINGULIER :p 
tu dois tout renommer ! Entity, Controller, Repository, templates, etc... dsl (et ça n'aurait pas du passer la review...)

2021-01-11 08:37 UTC, sblondeau commented on src/DataFixtures/PricesFixtures.php
> +class PricesFixtures extends Fixture
PriceFixutures

2021-01-11 08:37 UTC, sblondeau commented on src/Controller/AdminPricesController.php
> +        $price = new Prices();
new Price()

2021-01-11 08:37 UTC, sblondeau commented on src/Entity/Prices.php
> +class Prices
Price

2021-01-11 08:37 UTC, sblondeau commented on src/Entity/Prices.php
> +     * @Assert\Length(max="255", maxMessage="Le nom ne doit pas dépasser {{ value }} caractère.")
pas la peine d'ecrire le message d'erreur, il est géré par défaut par Sf si tu as mis la langue en français

2021-01-11 08:37 UTC, sblondeau commented on src/Entity/Prices.php
> +     * @Assert\NotBlank
un @Assert\Positive a ajouter je pense

2021-01-11 08:37 UTC, sblondeau commented on templates/admin_prices/_form.html.twig
> +{{ form_start(form) }}
templates/admin_price (à modif partout)

2021-01-11 08:37 UTC, sblondeau commented on migrations/Version20210106201915.php
> +final class Version20210106201915 extends AbstractMigration
tes migrations ne vont pas
tu as du oublié de faire un d:m:m quand tu as pull dev
là  tu ne fais que créer la table price donc tu ne devrais avoir qu'un seul fichier de migration et que un CREATE TABLE dedans

2021-01-11 11:11 UTC, calouvts submitted a review, later dismissed

2021-01-12 08:39 UTC, sblondeau requested changes

2021-01-12 08:39 UTC, sblondeau commented on migrations/Version20210111095303.php
> +        $this->addSql('DROP TABLE price');
y a un soucis, j'ia un CREATE TABLE suivi directement d'un DROP TABLE pour la meme table

2021-01-12 08:39 UTC, sblondeau commented on src/Entity/Price.php
> +     * @ORM\Column(type="string", length=255, nullable=true)
tu es sûr que la description est un varchar 255 et pas un type TEXT ? si oui, il me faut un Assert\Length à 255

2021-01-12 14:49 UTC, MaevaPllt approved these changes

2021-01-13 08:44 UTC, sblondeau approved these changes

2021-01-13 08:44 UTC, merged