Fix navbar
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #170
Opened 2021-01-11 11:48 UTC by KevinVanphavong

2021-01-11 12:48 UTC, bloic submitted a review, later dismissed

2021-01-12 10:50 UTC, sblondeau requested changes

2021-01-12 10:50 UTC, sblondeau commented on templates/base.html.twig
> +    <script src="https://kit.fontawesome.com/fed12f4e3a.js" crossorigin="anonymous"></script>
tu installes bien font awesome via yarn, donc pas besoin de le rappeler ici dans une balise script via un CDN 
fais juste un import de fontawesome dans ton fichier app.js (comme c'est fait pour bootstrap) et ça va le charger tout seul normalement

2021-01-12 11:25 UTC, MaevaPllt approved these changes

2021-01-12 11:29 UTC, sblondeau requested changes

2021-01-12 11:29 UTC, sblondeau commented on templates/base.html.twig
> +    <script src="https://kit.fontawesome.com/fed12f4e3a.js" crossorigin="anonymous"></script>
tu l'as pas supprimé ta balise script

2021-01-12 15:37 UTC, MaevaPllt approved these changes

2021-01-13 08:45 UTC, sblondeau approved these changes

2021-01-13 08:46 UTC, merged