add the typehint for property in User entity
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #172
Opened 2021-01-11 13:15 UTC by KevinVanphavong

2021-01-11 13:25 UTC, bloic submitted a review, later dismissed

2021-01-12 11:00 UTC, sblondeau requested changes

2021-01-12 11:00 UTC, sblondeau commented on migrations/Version20210111124233.php
> +final class Version20210111124233 extends AbstractMigration
non je devais avoir une migration avec seulement un ALTER pour ajouter prenom et nom
là tu dois encore avoir tous les autres fichiers de migration non ? 
donc 
- DROP ta database et récréé là (symonfy console d:d:d puis symfony console d:d:c)
- rejoue les migration (d:m:m)
- recharge les fixutres (d:f:l)
- là tu retrouves une structure de bdd correcte avant tes modif
- génère ta migration pour les modif => make:migration
- joue ta migration d:m:m
- test si tout est ok

2021-01-12 11:31 UTC, sblondeau requested changes

2021-01-12 11:31 UTC, sblondeau commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=255)
et manque les Assert

2021-01-12 11:34 UTC, KevinVanphavong commented on migrations/Version20210111124233.php
> +final class Version20210111124233 extends AbstractMigration
j'avais justement eu un problème  que je n'ai pas réussi à défaire, c'est pourquoi j'ai supprimé toutes mes migrations et drop ma BDD. Pour ensuite en refaire une entièrement. Ca fait que je n'ai plus qu'un seul fichier de mirgations qui est celui que tu vois ....

2021-01-12 15:37 UTC, MaevaPllt submitted a review, later dismissed

2021-01-13 08:48 UTC, sblondeau requested changes

2021-01-13 08:48 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Length(min="2", max="100")
pas de min sur les noms et prenoms je l'ai déjà dis !!!
le notBlank suffit. 
Le ministre actuel du numérique s'appelle "Cédric O" par ex...  tu voudrais lui refuser une séance de sophrologie ? c'est pas sympa !

2021-01-18 08:18 UTC, bloic approved these changes

2021-01-18 11:30 UTC, sblondeau approved these changes

2021-01-18 11:30 UTC, merged