S04 us41 upload
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #181
Opened 2021-01-12 20:13 UTC by calouvts

2021-01-13 07:55 UTC, MaevaPllt approved these changes

2021-01-13 08:55 UTC, sblondeau approved these changes

2021-01-13 08:56 UTC, sblondeau requested changes

2021-01-13 08:56 UTC, sblondeau commented on templates/event/show.html.twig
> +                <img class="img-fluid" src="/uploads/{{ event.picture }}" alt="{{ event.title }}">
il faut utiliser le {{vich_upload_asset

2021-01-13 08:56 UTC, sblondeau commented on migrations/Version20210109103501.php
> +final class Version20210109103501 extends AbstractMigration
tu ne devrais avoir qu'un seul fichier de migration avec seulement la modif propre à l'upload

2021-01-18 10:43 UTC, bloic approved these changes

2021-01-18 11:31 UTC, sblondeau approved these changes

2021-01-18 15:09 UTC, bloic approved these changes

2021-01-18 15:38 UTC, merged