change H on title and category
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #182
Opened 2021-01-12 20:21 UTC by calouvts

2021-01-13 07:54 UTC, MaevaPllt submitted a review, later dismissed

2021-01-13 09:00 UTC, sblondeau requested changes
fichier de migration en trop et image dans uploads ne doivent pas etre versionnées

2021-01-18 10:44 UTC, calouvts commented
j'avais fait une migration car j'avais eu un souci en changeant de branche ><

2021-01-18 10:53 UTC, bloic approved these changes

2021-01-18 10:58 UTC, bloic approved these changes

2021-01-18 11:32 UTC, sblondeau approved these changes

2021-01-18 11:32 UTC, merged