initialization commit
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #2
Opened 2020-12-03 13:04 UTC by KevinVanphavong

2020-12-03 14:48 UTC, sblondeau requested changes
je ne comprends pas ce que tu as voulu faire ? j'ai juste 2 fichiers vides

2020-12-03 16:31 UTC, KevinVanphavong commented
> je ne comprends pas ce que tu as voulu faire ? j'ai juste

2020-12-04 08:06 UTC, sblondeau requested changes

2020-12-04 08:06 UTC, sblondeau commented on templates/base.html.twig
> +    <link rel="preconnect" href="https://fonts.gstatic.com">
c'est quoi ce "preconnect" ? inutile ? et répété plusieurs fois en plus

2020-12-04 08:06 UTC, sblondeau commented on templates/home/index.html.twig
> +    {#    <section class="d-flex justify-content-ar0
code commenté

2020-12-04 08:06 UTC, sblondeau commented on templates/home/index.html.twig
> +    <div style="color: black; background-color: #9FC5E9; width:100%; height: 180px; border: 1px solid black">Couleur primaire</div>
je vous demande pas d'afficher votre style guide ici, et dans tous les cas, ce serait pas avec un attribut style !
tu peux m'enlever tout ça, garde que le H1

2020-12-04 09:04 UTC, sblondeau requested changes

2020-12-04 09:04 UTC, sblondeau commented on templates/base.html.twig
> +    <link href="https://fonts.googleapis.com/css2?family=Arizonia&display=swap" rel="stylesheet">
refait ton import de font stp
là tu as 
<link href="https://fonts.googleapis.com/css2?family=PT+Serif&display=swap" rel="stylesheet">    
   <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital@0;1&display=swap" rel="stylesheet">    
   <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital@1&display=swap" rel="stylesheet">    
  <link href="https://fonts.googleapis.com/css2?family=Arizonia&display=swap" rel="stylesheet">
va sur Google font, tu sélectionnes en une fois toutes les font que tu veux, et tu auras qu'une seule ligne à import (et perso je préfère utiliser @import que les balises link) ^^
je vois qu'il t'ajoute le préconnect dans l'import, je connaissais pas, laisse en qu'un seul dans ce cas

2020-12-04 09:42 UTC, sblondeau approved these changes

2020-12-04 09:42 UTC, merged