adding edit form for user in personnal page
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #204
Opened 2021-01-18 15:47 UTC by KevinVanphavong

2021-01-18 18:38 UTC, bloic approved these changes

2021-01-19 10:00 UTC, sblondeau requested changes

2021-01-19 10:00 UTC, sblondeau commented on src/Controller/AdminUser.php
>       * @IsGranted("ROLE_USER", statusCode=404)
pourquoi un statusCode 404 ? si l'utilisateur n'est pas authorisé, y a un status code 401 normalement ;-) mais c'est géré automatiquement, pas la peine de le préciser

2021-01-19 10:00 UTC, sblondeau commented on src/Controller/AdminUser.php
> +    public function myAccount(Request $request, User $user): Response
pas la pein de passer un param $user
tu récup direct $this->getUser() dans la méthode et tu as l'utilsateur actuellement connecté

2021-01-19 10:00 UTC, sblondeau commented on src/Controller/AdminUser.php
> +    public function myAccount(Request $request, User $user): Response
voire encore mieux, tu ne recup pas du tout user et tu utilises app.user dans Twig (ce que tu fais d'ailleurs donc ton $user te sers vraiment à rien ;-))

2021-01-20 12:31 UTC, bloic approved these changes

2021-01-20 12:41 UTC, sblondeau approved these changes

2021-01-20 12:41 UTC, merged