S04 us65 search function
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #210
Opened 2021-01-18 22:06 UTC by calouvts

2021-01-19 07:55 UTC, bloic submitted a review, later dismissed

2021-01-19 10:03 UTC, sblondeau requested changes

2021-01-19 10:03 UTC, sblondeau commented on src/Repository/EventRepository.php
> +use http\Env\Response;
pas le bon objet Response, ça doit etre le httpFoundation

2021-01-19 10:03 UTC, sblondeau commented on src/Repository/EventRepository.php
> +    public function findLikeName(string $name, int $archive): array
c'est pas mal mais optimisable, je montre ça ne Livecoding tout à l'heure

2021-01-22 13:32 UTC, sblondeau approved these changes

2021-01-22 13:32 UTC, merged