fix message flash on edit and delete
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #213
Opened 2021-01-19 14:21 UTC by bloic

2021-01-19 14:26 UTC, cedric-n submitted a review, later dismissed

2021-01-19 14:43 UTC, sblondeau requested changes

2021-01-19 14:43 UTC, sblondeau commented on src/Controller/AdminPriceController.php
> +            $this->addFlash('success', 'Le tarif à bien était modifier');
**a** bien été modifié !

2021-01-19 14:43 UTC, sblondeau commented on src/Controller/AdminPriceController.php
> +            $this->addFlash('success', 'Le tarif à bien était supprimé');
**a** bien **été**

2021-01-20 14:55 UTC, sblondeau requested changes

2021-01-20 14:55 UTC, sblondeau commented on src/Controller/AdminPriceController.php
> +            $this->addFlash('success', 'Le tarif a bien été supprimer');
mais non tu me refais des fautes !
a bien été supprimé, ajouté, modifé

2021-01-20 21:57 UTC, MaevaPllt approved these changes

2021-01-21 09:34 UTC, sblondeau approved these changes

2021-01-21 09:34 UTC, merged