Fix homepage image
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #222
Opened 2021-01-20 18:40 UTC by KevinVanphavong

2021-01-20 19:13 UTC, cedric-n approved these changes

2021-01-21 09:36 UTC, sblondeau requested changes
plein d'images bien trop lourdes (et en plus meme pas utilisées dans le code ?)

2021-01-21 12:33 UTC, bloic approved these changes

2021-01-21 14:32 UTC, sblondeau approved these changes

2021-01-21 14:32 UTC, merged