changing layout, similar to navbar client
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #223
Opened 2021-01-20 19:31 UTC by KevinVanphavong

2021-01-20 19:35 UTC, bloic approved these changes

2021-01-21 09:37 UTC, sblondeau requested changes

2021-01-21 09:37 UTC, sblondeau commented on templates/itemAdmin/_navbarAdmin.html.twig
> +{#    <a class="navbar-brand nav-link text-center text-lg-left" href="#">#}
code commenté

2021-01-21 12:32 UTC, bloic approved these changes

2021-01-21 14:44 UTC, sblondeau submitted a review, later dismissed

2021-01-22 08:03 UTC, sblondeau approved these changes

2021-01-22 08:04 UTC, merged