S04 us72 add logo
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #241
Opened 2021-01-21 22:08 UTC by calouvts

2021-01-21 23:14 UTC, bloic reviewed
tu as mis tout tes fichier de crud l'edit,show etc... dans ta fonction add

2021-01-21 23:14 UTC, bloic commented on templates/admin_logo/_delete_form.html.twig
> +<form method="post" action="{{ path('logo_delete', {'id': logo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
ne doit pas figurer dans le add

2021-01-21 23:14 UTC, bloic commented on templates/admin_logo/edit.html.twig
> +{% extends 'base.html.twig' %}
idem ne doit pas être dans le add

2021-01-22 09:44 UTC, bloic approved these changes

2021-01-22 13:33 UTC, sblondeau requested changes

2021-01-22 13:33 UTC, sblondeau commented on src/Entity/Logo.php
> +     * @ORM\Column(type="string", length=255, nullable=true)
pas logique que le nom soit nullable non ? 
je rajouterai un Assert\NotBlank aussi

2021-01-22 14:39 UTC, sblondeau approved these changes

2021-01-22 14:39 UTC, merged