S04 us72 index logo
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #247
Opened 2021-01-22 14:45 UTC by calouvts

2021-01-22 14:53 UTC, bloic approved these changes

2021-01-22 14:55 UTC, cedric-n reviewed
$manager->flush() il doit être en dehors de la boucle non ?

2021-01-22 14:58 UTC, cedric-n reviewed
$manager->flush doit être en dehors de la boucle non ?

2021-01-22 15:41 UTC, sblondeau requested changes

2021-01-22 15:41 UTC, sblondeau commented on templates/admin_logo/index.html.twig
> +                <th>Company</th>
trad

2021-01-22 15:52 UTC, calouvts commented on templates/admin_logo/index.html.twig
> +                <th>Company</th>
quand le cerveau crame le jeudi soir à minuit on traduit des trucs en anglais alors qu'ils devraient être en français.....

2021-01-22 15:54 UTC, MaevaPllt submitted a review, later dismissed

2021-01-22 15:55 UTC, sblondeau submitted a review, later dismissed

2021-01-22 17:46 UTC, KevinVanphavong approved these changes

2021-01-23 19:56 UTC, sblondeau approved these changes

2021-01-23 19:56 UTC, merged