Fix reports admin option select
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #253
Opened 2021-01-22 17:31 UTC by KevinVanphavong

2021-01-22 17:42 UTC, calouvts submitted a review, later dismissed

2021-01-25 08:36 UTC, sblondeau requested changes

2021-01-25 08:36 UTC, sblondeau commented on src/Form/ReportType.php
> +                    return strtoupper($user->getLastname() ?: 'John')
je te conseille plutot de creer une méthode getFullName() dans l'entity User, qui renverra ta chaine concaténée
et là tu appelles 'choice_label' => 'fullName'
et ne renvoie pas John Doe j'ai peur que ça pose des pb d'affichage dans ce cas.

2021-01-25 10:52 UTC, bloic approved these changes

2021-01-25 13:51 UTC, sblondeau requested changes

2021-01-25 13:51 UTC, sblondeau commented on src/Form/ReportType.php
> +                'choice_label' => function (User $user) {
non fais direct 'choice_label' => 'fullname'
il va aller chercher le getFullname() s'il existe

2021-01-25 14:38 UTC, sblondeau approved these changes

2021-01-25 14:38 UTC, merged