S05 us75 upload logo
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #261
Opened 2021-01-25 10:56 UTC by calouvts

2021-01-25 11:19 UTC, MaevaPllt submitted a review, later dismissed

2021-01-25 13:52 UTC, sblondeau requested changes

2021-01-25 13:52 UTC, sblondeau commented on src/Entity/Logo.php
> +     * @Vich\UploadableField(mapping="logo_file", fileNameProperty="logo")
ajoute des assert sur les types d'images et taille d'image

2021-01-25 14:22 UTC, calouvts commented on src/Entity/Logo.php
> +     * @Vich\UploadableField(mapping="logo_file", fileNameProperty="logo")
Ah yes ! my bad sorry complètement zappé ><

2021-01-25 14:24 UTC, MaevaPllt submitted a review, later dismissed

2021-01-25 14:39 UTC, sblondeau requested changes

2021-01-25 14:39 UTC, sblondeau commented on src/Entity/Logo.php
> +     * @Assert\File(maxSize="1000k", mimeTypes={"image/jpeg", "image/png", "image/pdf"})
image/pdf ? c'est pas un type mime non? jpeg et png c'est bien

2021-01-25 21:27 UTC, sblondeau submitted a review, later dismissed

2021-01-26 08:40 UTC, bloic approved these changes

2021-01-26 09:34 UTC, merged