Us user filter for admin reports
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #269
Opened 2021-01-25 21:12 UTC by KevinVanphavong

2021-01-25 22:29 UTC, calouvts requested changes

2021-01-25 22:29 UTC, calouvts commented on src/Repository/ReportRepository.php
> +        return $this->createQueryBuilder('r')
je pense que t'avais un autre moyen pour ton tri que passer par le Query Builder, mais après je ne sais pas si c'est problématique ou non, (du type utiliser les fonctions déjà disponibles en adjoingrant un tri ce doit etre possible. )

2021-01-25 22:29 UTC, calouvts commented on templates/itemAdmin/_navbarAdmin.html.twig
> +                <a class="nav-link text-light text-uppercase" href="{{ path("admin_reports") }}">Comptes rendues</a>
enlever le e de "rendues" et mettre un - .

2021-01-26 08:45 UTC, calouvts approved these changes

2021-01-26 09:37 UTC, sblondeau approved these changes

2021-01-26 09:37 UTC, merged