adding section welcome
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #27
Opened 2020-12-08 20:42 UTC by KevinVanphavong

2020-12-08 20:53 UTC, MaevaPllt approved these changes

2020-12-09 08:33 UTC, sblondeau requested changes

2020-12-09 08:33 UTC, sblondeau commented on assets/styles/home.scss
> +    position: absolute;
avec des flexbox (en space-between) par ex, ça serait pas mieux? 
là j'ai testé le texte va etre un peu trop collé en haut si tu ajoutes une navbar non ? 
et le bouton est trop petit, pas assez lisible, le texte en noir sur bleu clair rend pas très bien. :p 
je chipote sur le style mais sinon c'est bien ;-)

2020-12-09 15:05 UTC, sblondeau submitted a review, later dismissed

2020-12-09 15:45 UTC, merged