S04 us76 password reinitialisation
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #284
Opened 2021-01-26 15:53 UTC by cedric-n

2021-01-26 16:06 UTC, bloic submitted a review, later dismissed

2021-01-26 16:24 UTC, sblondeau requested changes

2021-01-26 16:24 UTC, sblondeau commented on src/Controller/ResetPasswordController.php
> +            throw $this->createNotFoundException('No reset password token found in the URL or in the session.');
te manque des traductions, je te laisse checker un peu partout dans les fichiers générés

2021-01-26 21:46 UTC, bloic approved these changes

2021-01-27 08:09 UTC, sblondeau approved these changes

2021-01-27 08:21 UTC, merged