adding section2 introducing the client
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #29
Opened 2020-12-08 21:25 UTC by KevinVanphavong

2020-12-09 08:27 UTC, MaevaPllt submitted a review, later dismissed

2020-12-09 08:40 UTC, sblondeau requested changes

2020-12-09 08:40 UTC, sblondeau commented on templates/home/index.html.twig
> +    <h1>Projet 3 - Sophrologie | Entreprise INSPIRE et EXPIR</h1>
titre à modifier (enleve Projet 3 :p) et manque une E à EXPIRE (si tu veux le laisser)

2020-12-09 08:40 UTC, sblondeau commented on templates/home/index.html.twig
>  {% block title %}{{ parent() }} | Sophrologie{% endblock %}
ici mettre le nom INSPIRE & EXPIRE plutot que "sophro" ?

2020-12-09 08:40 UTC, sblondeau commented on templates/home/index.html.twig
> +            <img class="sophro-picture mr-lg-5 mb-sm-5" src="{{ asset('build/images/pp-cliente.png') }}" alt="picture of the sophrologist">
le alt doit etre en français

2020-12-09 08:40 UTC, sblondeau commented on templates/home/index.html.twig
> +            <p class="mb-4">(Texte à remplir)</p>
ça sera administrable ça ? si oui faut que ça soit relié à une BDD, sinon tu n'as pas un texte déjà ? 
il faut éviter de mettre "texte à remplir" ou du lorem car c'est un coup à oublier et de pousser en prod le site comme ça :/

2020-12-09 08:40 UTC, sblondeau commented on assets/styles/app.scss
> +    height: 220px;
tu as pas la meme width/height et du coup l'image est ovale, c'est pas très joli

2020-12-09 08:54 UTC, KevinVanphavong commented on templates/home/index.html.twig
> +            <p class="mb-4">(Texte à remplir)</p>
Pour cette section je me doutais de ta réponse. Cette partie est non administrable, ce sera une partie statique avec du texte précis fourni par la cliente. Vu qu'on n'a pas encore les infos (à venir prochainement) j'ai mis ça au lieu du lorem et j'ai également créé une US en fix pour ca donc ce ne sera pas oublier ;)

2020-12-10 08:28 UTC, sblondeau approved these changes

2020-12-10 08:28 UTC, merged