adding section3 what is sofrolog
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #30
Opened 2020-12-08 21:35 UTC by KevinVanphavong

2020-12-09 08:37 UTC, MaevaPllt submitted a review, later dismissed

2020-12-09 08:43 UTC, sblondeau requested changes

2020-12-09 08:43 UTC, sblondeau commented on templates/home/index.html.twig
> +    <h1>Projet 3 - Sophrologie | Entreprise INSPIRE et EXPIR</h1>
idem que la PR précédente sur le H1 et le block title

2020-12-09 08:43 UTC, sblondeau commented on templates/home/index.html.twig
> +            <p>(Texte à remplir)</p>
idem est-ce administrable ? si oui BDD, si non recup du texte ?

2020-12-09 08:43 UTC, sblondeau commented on templates/home/index.html.twig
> +                <img src="https://img.icons8.com/officel/80/000000/reflector-bulb.png" class="ampoule mb-4 mr-4"/>
utilise pas un lien direct vers le site de l'icon, il faut la mettre en local pour éviter les liens morts futurs
choisi un set d'icones cohérentes tout le long du site
flaticon est vraiment pas mal comme site

2020-12-09 10:33 UTC, KevinVanphavong commented on templates/home/index.html.twig
> +            <p>(Texte à remplir)</p>
C'est du texte en dur. J'ai également créé un fix en issue pour rattraper ca

2020-12-09 16:24 UTC, MaevaPllt approved these changes

2020-12-10 08:54 UTC, sblondeau approved these changes

2020-12-10 10:03 UTC, MaevaPllt approved these changes

2020-12-10 10:34 UTC, merged