S01 us35 event
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #32
Opened 2020-12-08 22:46 UTC by calouvts

2020-12-09 10:11 UTC, KevinVanphavong submitted a review, later dismissed

2020-12-09 14:29 UTC, sblondeau requested changes
Il me manque des fixtures

2020-12-09 14:29 UTC, sblondeau commented on migrations/Version20201208194229.php
> +        $this->addSql('CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, date DATE NOT NULL, description LONGTEXT NOT NULL, url VARCHAR(255) NOT NULL, PRIMARY KEY(id)) D
là j'ai une migration qui me créé une table news qui n'existe pas (plus ?)

2020-12-09 14:29 UTC, sblondeau commented on migrations/Version20201208194229.php
> +        $this->addSql('CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, date DATE NOT NULL, description LONGTEXT NOT NULL, url VARCHAR(255) NOT NULL, PRIMARY KEY(id)) D
fais le ménage et fais en sorte de n'avoir qu'une migration propre par PR

2020-12-10 09:43 UTC, MaevaPllt approved these changes

2020-12-10 09:54 UTC, calouvts commented on migrations/Version20201208194229.php
> +        $this->addSql('CREATE TABLE news (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, date DATE NOT NULL, description LONGTEXT NOT NULL, url VARCHAR(255) NOT NULL, PRIMARY KEY(id)) D
ménage fait dans les migrations, fixtures mode simple (sans le faker effectuées)

2020-12-10 10:36 UTC, sblondeau submitted a review, later dismissed

2020-12-10 10:48 UTC, MaevaPllt approved these changes

2020-12-10 12:33 UTC, MaevaPllt approved these changes

2020-12-10 12:48 UTC, merged