fix_arrow_up_pages
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #386
Opened 2021-02-01 16:33 UTC by MaevaPllt

2021-02-01 16:40 UTC, calouvts approved these changes

2021-02-01 16:59 UTC, calouvts approved these changes

2021-02-01 23:08 UTC, sblondeau requested changes

2021-02-01 23:08 UTC, sblondeau commented on assets/styles/collectiveSessions.scss
> +#up {
tu répètes 5-6 fois le meme code dans des fichiers différents. DRY ! 
tu peux mettre le CSS dans un fichier commun à ces pages
de plus coté html de la fleche, tu pourrais faire un fichier twig que tu incluerait pour etre plus DRY egalement.
Bref c'est optimisable 

Et plutot que de mettre une image, ça porurait etre une icone en SVG

2021-02-02 11:23 UTC, MaevaPllt commented on assets/styles/collectiveSessions.scss
> +#up {
C'est corrigé, j'ai include la flèche, mis une image svg et le css dans le fichier commun !

2021-02-02 11:36 UTC, calouvts approved these changes

2021-02-02 13:16 UTC, sblondeau approved these changes

2021-02-02 13:16 UTC, merged