adding specific text from our client
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #71
Opened 2020-12-11 15:24 UTC by KevinVanphavong

2020-12-11 20:59 UTC, calouvts submitted a review, later dismissed

2020-12-12 23:12 UTC, sblondeau requested changes

2020-12-12 23:12 UTC, sblondeau commented on templates/home/index.html.twig
> +                <p>Diplômée de l’Ecole Supérieur de Sophrologie Appliquée (ESSA) de Vincennes</p>
Supérieur**e**

2020-12-12 23:12 UTC, sblondeau commented on templates/home/index.html.twig
> +    <section class="section2 jumbotron container bg-white py-5 px-0 mb-0 d-lg-flex text-lg-left">
on est pas jumbotron + container, d'autant que tu réouvres un container juste en dessous... trop de classes inutiles

2020-12-12 23:12 UTC, sblondeau commented on templates/home/index.html.twig
> +            <div class="col-10 d-flex flex-column">
ne me mets pas des d-flex partout si c'est pas utile !

2020-12-14 11:30 UTC, MaevaPllt approved these changes

2020-12-15 07:55 UTC, sblondeau approved these changes

2020-12-15 07:55 UTC, merged