adding section4 for specialities
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #72
Opened 2020-12-12 14:20 UTC by KevinVanphavong

2020-12-14 11:32 UTC, MaevaPllt approved these changes

2020-12-15 08:21 UTC, sblondeau requested changes

2020-12-15 08:21 UTC, sblondeau commented on templates/home/index.html.twig
> +            <div class="speciality p-2 text-white col-lg-4 col-md-4 col-12">
la classe col-12 est inutile car appliquée par défaut par bootstrap

2020-12-15 12:17 UTC, MaevaPllt approved these changes

2020-12-15 14:34 UTC, sblondeau approved these changes

2020-12-16 09:49 UTC, merged