create entity for adding new speciality then
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #73
Opened 2020-12-12 15:49 UTC by KevinVanphavong

Create entity for the speciality in order to :
- make related fixtures
- adding form for CRUDing 
- make migration to database

2020-12-14 15:45 UTC, cedric-n approved these changes

2020-12-15 08:26 UTC, sblondeau requested changes
dans l'onglet projet, je n'ai pas d'US 14 ? par contre j'ai une seule tache qui est "ajouter des specialités". 
ce n'est PAS une US ;-) il faudrait au minimum une page qui liste ces spéciality  ? nettoyer bien votre onglet projet et revois cette US

2020-12-15 08:26 UTC, sblondeau commented on src/Entity/Speciality.php
> +     * @Assert\Length(max="255", maxMessage="Vous ne pouvez dépasser la limite de {{ limit }} caractères")
Inutile de t'amuser à traduire les messages d'erreur comme je vous ai montré dans le dernier LC et comme s'est indiqué dans la quete ! il suffit d'activer la langue "fr" dans le fichier de config des translations
Ca te fera gagner pas mal de temps

2020-12-15 19:07 UTC, cedric-n approved these changes

2020-12-16 12:30 UTC, sblondeau approved these changes

2020-12-16 12:30 UTC, merged