S02 us45 create event
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #77
Opened 2020-12-13 22:56 UTC by calouvts

A prendre dans l'ordre create/update/read/delete

2020-12-14 08:49 UTC, bloic approved these changes

2020-12-14 09:47 UTC, sblondeau requested changes
hum cette PR ressemble fortement à la PR précédente, tu as pas un soucis dans tes branches ? :/  car je vais avoir les memes retours là ...

2020-12-14 10:43 UTC, calouvts commented
résolu par rapport aux commentaires effectués sur la branche Read :+1: 

 templates/admin_event/new.html.twig
    {% endblock %}
{% block body %}

    <section class="sheettop">

SB =>
niveau balises c'est plutot des sections dans un main que le contraire

=>mmodifié


 src/Entity/Event.php
     */
    private ?string $url;

    /**
     * @ORM\Column(type="date", nullable=true)
SB=> tu as un Assert\Date qui existe

pv =>du coup j'ai utilisé @Assert\Type("DateTime") sur la base de symfony/symfony#35378 je ne sais pas si c'est la bonne option


 src/Form/EventType.php
                ],
            ])
            ->add('description', TextareaType::class, [
    
SB => attention tous les labels ont pas une majuscule au début, je ne sais plus s'il en ajoute une auto sur le rendu final


PV => My bad= >parfaitement exact, trop concentrée sur le fait d'essayer de faire fonctionner l'ajout.j'ai pas fait attention au reste.

2020-12-15 08:27 UTC, sblondeau requested changes

2020-12-15 08:27 UTC, sblondeau commented on src/DataFixtures/EventFixtures.php
> +            $event1->setEventdate(new DateTime());
1/ ajoute Faker plutot dans tes fixtures
2/ ta variable devrait s'appeler $event et pas $event1 non ?

2020-12-15 14:35 UTC, sblondeau approved these changes

2020-12-15 14:36 UTC, merged