S01US23_contact_form_add_form_symfony
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #83
Opened 2020-12-16 14:05 UTC by MaevaPllt

2020-12-16 14:10 UTC, cedric-n submitted a review, later dismissed

2020-12-17 08:10 UTC, sblondeau requested changes

2020-12-17 08:10 UTC, sblondeau commented on src/Entity/Contact.php
> +     * @Assert\NotBlank(message="Merci de saisir votre prénom")
pas besoin de tout traduire, comme j'ai montré en LC ou comme s'est indiqué dans la quete, il faut passer Sf en "français" (fichier config/package/translations)
ça te simplifiera la vie

2020-12-17 08:10 UTC, sblondeau commented on src/Form/ContactType.php
> +                    'Sélectionnez un thème' => 'ChoiceSelect',
ne mets pas cette ligne "Sélectionnez un thème" qui ne sert à rien
au pire tu as une option https://symfony.com/doc/current/reference/forms/types/choice.html#empty-data

2020-12-17 08:10 UTC, sblondeau commented on src/Form/ContactType.php
> +                    'placeholder' => 'Saisissez votre message...',
si tu mets un placeholder, mets en sur tous les champs

2020-12-17 08:10 UTC, sblondeau commented on .gitignore
> +/.env
non le .env ne doit PAS etre ignoré
mais le MAILER_DSN avec les données confidentielles se met dans le env.local

2020-12-17 08:10 UTC, sblondeau commented on templates/contact/mail.html.twig
> +<style>
pourquoi une balise style vide ?

2020-12-17 08:10 UTC, sblondeau commented on templates/contact/mail.html.twig
> +
structure mieux le mail, avec un vrai fichier HTML

2020-12-17 08:30 UTC, MaevaPllt commented on src/Entity/Contact.php
> +     * @Assert\NotBlank(message="Merci de saisir votre prénom")
C'est fait !

2020-12-17 08:32 UTC, MaevaPllt commented on src/Form/ContactType.php
> +                    'Sélectionnez un thème' => 'ChoiceSelect',
C'est fait aussi !

2020-12-17 08:48 UTC, MaevaPllt commented on src/Form/ContactType.php
> +                    'placeholder' => 'Saisissez votre message...',
Rectifié !

2020-12-17 08:49 UTC, MaevaPllt commented on templates/contact/mail.html.twig
> +<style>
J'ai fais la structure mais j'ai oublié de styliser dedans

2020-12-17 08:51 UTC, MaevaPllt commented on templates/contact/mail.html.twig
> +
Corrigé !

2020-12-17 11:37 UTC, calouvts approved these changes

2020-12-17 14:29 UTC, sblondeau requested changes

2020-12-17 14:29 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->to('maevapllt@gmail.com')
non pas en dur ! il faut que tu passes par un paramètre comme c'est expliqué dans la quete ;-)

2020-12-17 19:22 UTC, MaevaPllt commented on src/Controller/ContactController.php
> +                ->to('maevapllt@gmail.com')
C'est ok !

2020-12-17 19:32 UTC, calouvts approved these changes

2020-12-17 19:33 UTC, bloic submitted a review, later dismissed

2020-12-18 08:10 UTC, sblondeau requested changes

2020-12-18 08:10 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->from('admin@monsite.com')
c'est celle-ci le mailer_from

2020-12-18 08:10 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->to($this->getParameter('mailer_from'))
et pour cette méthode un 2nd paramètre mailer_to

2020-12-18 08:10 UTC, sblondeau commented on src/Controller/ContactController.php
> +                ->subject('Message de contact')
je pensais que tu voulais mettre $contact->getTheme en sujet ? mais pas obligatoire, je te laisse voir ce qui te semble le plus pertinent

2020-12-18 09:36 UTC, sblondeau approved these changes

2020-12-18 09:36 UTC, merged