fix_section_timetable_style
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #88
Opened 2020-12-16 17:56 UTC by MaevaPllt

2020-12-16 18:34 UTC, cedric-n submitted a review, later dismissed

2020-12-17 19:32 UTC, cedric-n submitted a review, later dismissed

2020-12-18 13:41 UTC, KevinVanphavong approved these changes

2020-12-18 13:54 UTC, sblondeau requested changes

2020-12-18 13:54 UTC, sblondeau commented on templates/contact/index.html.twig
> +            <div class="col-lg-4 col-sm-10 offset-lg-1 pt-5 timetable-image d-flex justify-content-center">
pas de col-12 c'est inutile

2020-12-18 15:09 UTC, KevinVanphavong submitted a review, later dismissed

2020-12-18 15:20 UTC, sblondeau approved these changes

2020-12-18 15:30 UTC, merged