add delete part in speciality admin
WildCodeSchool/orleans-php-202009-project-sophrologie pull request #94
Opened 2020-12-17 11:45 UTC by KevinVanphavong

2020-12-17 12:02 UTC, cedric-n approved these changes

2020-12-17 12:03 UTC, MaevaPllt submitted a review, later dismissed

2020-12-17 16:45 UTC, sblondeau requested changes

2020-12-17 16:45 UTC, sblondeau commented on templates/speciality/_delete.html.twig
> +      onsubmit="return confirm('Are you sure you want to delete this item?');">
le message dans on onsubmit à traduire

2020-12-17 19:46 UTC, MaevaPllt approved these changes

2020-12-18 08:20 UTC, sblondeau approved these changes

2020-12-18 08:20 UTC, sblondeau requested changes

2020-12-18 08:20 UTC, sblondeau commented on templates/speciality/_delete.html.twig
> +      onsubmit="return confirm('Êtes vous sûre de bien vouloir supprimer cet item ?');">
cette spécialité plutot que cet item ? 

et pas de style en inline stp ! CSS dans une classe

2020-12-18 09:01 UTC, sblondeau approved these changes

2020-12-18 09:01 UTC, merged